"use client";
import { usePathname } from "next/navigation";
import StepBar from "./components/StepBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Upload Music",
//   description: "Generated by Kyle",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  let currentStep = 1;
  if (pathname === "/edit") {
    currentStep = 2;
  } else if (pathname === "/processing") {
    currentStep = 3;
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col justify-start items-center min-h-screen`}
      >
        <h1 className="text-4xl font-bold my-10 text-[#0F0F0F]">
          Upload Your Music
        </h1>
        <StepBar currentStep={currentStep} />
        {children}
      </body>
    </html>
  );
}
